uploads = []

[[generated]]
id = "AtQZRD88uw6LMNH0rTph-"
uri = "file://attached_assets/generated_images/padhosuno_splash.png"
type = "image"
title = "padhosuno splash screen"

[[outputs]]
id = "wFsxm125JEZHu_ragzx9w"
uri = "file://Padho-Suno.md"
type = "text"
title = "PadhoSuno — Full Project Documentation"

[[outputs]]
id = "voI7VX5GRz76shbcD6UxB"
uri = "file://PadhoSuno - Full Project Documentation.md"
type = "text"
title = "PadhoSuno — Full Project Documentation"
